//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LA3DataTransfer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Account
    {
        public int account_id { get; set; }
        public Nullable<int> cust_id { get; set; }
        public Nullable<decimal> ret_price { get; set; }
        public Nullable<decimal> tot_amount { get; set; }
        public Nullable<short> period { get; set; }
        public Nullable<decimal> payment { get; set; }
        public Nullable<decimal> left_to_pay { get; set; }
        public Nullable<decimal> overdue_amount { get; set; }
        public Nullable<System.DateTime> last_checked { get; set; }
        public Nullable<System.DateTime> next_payment { get; set; }
        public bool posted { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public bool monthly { get; set; }
        public bool printed_form { get; set; }
        public string pay_off { get; set; }
        public Nullable<decimal> pay_off_amount { get; set; }
        public string notes { get; set; }
    }
}
