//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LA3DataTransfer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Collector
    {
        public int collector_id { get; set; }
        public string notes { get; set; }
        public string name { get; set; }
    }
}
