//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LA3DataTransfer.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    //using System.Data.Objects;
    //using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class ST_Entities : DbContext
    {
        public ST_Entities()
            : base("name=ST_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ST_Collector> ST_Collector { get; set; }
        public DbSet<ST_Account> ST_Account { get; set; }
        public DbSet<ST_Customer> ST_Customer { get; set; }
        public DbSet<ST_Payment> ST_Payment { get; set; }
        public DbSet<Parameter> Parameters { get; set; }
    
        //public virtual int TruncateTables()
        //{
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TruncateTables");
        //}
    
        //public virtual int TruncateTables1()
        //{
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TruncateTables1");
        //}
    }
}
