//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LA3DataTransfer.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ST_Payment
    {
        public int Payment_id { get; set; }
        public int account_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string Note { get; set; }
        public bool Sundry { get; set; }
        public Nullable<double> Left_to_pay { get; set; }
    }
}
